const app = document.querySelector('#app');
const STORAGE_KEY = 'huggy-prototype-state';
const AUTH_STORAGE_KEY = 'huggy-auth-session';
const AUTH_CONFIG = window.HUGGY_AUTH_CONFIG || {};

const copy = {
  fr: {
    promo: 'Économise environ 20% avec le paiement annuel',
    hello: 'Bonjour, bienvenue.',
    emptySubtitle: 'Décrivez le fichier à créer, ou déposez le vôtre à transformer.',
    placeholder: 'Ex : un budget mensuel par catégorie',
    editPlaceholder: 'Décrivez la modification à apporter à ce fichier…',
    generate: 'Générer le fichier',
    attach: 'Joindre un fichier Excel',
    newFile: 'Nouveau fichier',
    search: 'Rechercher un fil',
    noFiles: 'Aucun fichier encore',
    filesReady: 'fichier · Prêt',
    fileStored: 'Vos fichiers sont enregistrés sur cet appareil. Téléchargez ce que vous souhaitez conserver.',
    budget: 'Budget Freelance',
    sales: 'Suivi des Ventes',
    format: 'Mettre en forme',
    sort: 'Trier par date',
    preview: 'Aperçu',
    download: 'Télécharger',
    continue: 'Continuer à modifier',
    context: 'Contexte',
    terms: 'En générant, vous acceptez nos',
    cleanPrompt: 'Nettoie et mets en forme ce tableau',
    sortPrompt: 'Réordonne ce fichier par date',
    filePrompt: 'Crée un tableau de suivi des ventes avec date, produit, quantité et total.',
    stock: 'Gestion de stock', cash: 'Caisse quotidienne', invoice: 'Facture simple', payroll: 'Suivi de paie',
  },
  en: {
    promo: 'Save about 20% with annual billing',
    hello: 'Hello, there.',
    emptySubtitle: 'Describe the file to create, or drop yours to transform.',
    placeholder: 'e.g. a monthly budget by category',
    editPlaceholder: 'Describe the change to make to this file…',
    generate: 'Generate file', attach: 'Attach an Excel file', newFile: 'New file', search: 'Search threads',
    noFiles: 'No files yet', filesReady: 'file · Ready', fileStored: 'Files are stored on this device. Download anything you want to keep.', stock: 'Stock tracker', cash: 'Daily cashbook', invoice: 'Simple invoice', payroll: 'Payroll tracker',
    budget: 'Freelance Budget', sales: 'Sales Dashboard', format: 'Clean & format', sort: 'Sort by date', preview: 'Preview', download: 'Download', continue: 'Continue editing', context: 'Context', terms: 'By generating, you agree to our', cleanPrompt: 'Clean and format this table', sortPrompt: 'Sort this file by date', filePrompt: 'Create a sales tracker with date, product, quantity and total.',
  },
};

const defaults = { lang: 'fr', view: 'marketing', collapsed: false, promo: true, menu: false, modal: null, accountTab: 'profile', accountEdit: null, emailMenu: false, sheet: 'sales', generating: false, progress: 0, prompt: '', editPrompt: '', files: [], current: null, trialUsed: false, plan: 'free', generationCount: 0, generationLimit: 1, attachedFile: null, error: '', notice: '', sessionId: '', checkoutPlan: null, pendingCheckoutPlan: null, billing: 'monthly', checkoutLoading: false, authMode: 'login', authLoading: false, authError: '', authMessage: '', authUser: null };
let state = loadState();
function loadState() { try { const stored = JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}'); const files = Array.isArray(stored.files) ? stored.files.map(file => ({ ...file, history: Array.isArray(file.history) && file.history.length ? file.history : [{ version: Number(file.version || 1), prompt: file.prompt || '', workbook: file.workbook, createdAt: new Date().toISOString() }] })) : []; return { ...defaults, ...stored, files, view: 'marketing', sessionId: '', authUser: null, generating: false, modal: null, menu: false }; } catch { return { ...defaults }; } }
function save() { localStorage.setItem(STORAGE_KEY, JSON.stringify({ ...state, menu: false, modal: null, generating: false })); }
function t(key) { return copy[state.lang][key] || key; }
function esc(value) { return String(value).replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[c])); }

function authHeaders(accessToken = authSession()?.access_token) { return accessToken ? { authorization: `Bearer ${accessToken}` } : {}; }
function authSession() { try { return JSON.parse(localStorage.getItem(AUTH_STORAGE_KEY) || 'null'); } catch { return null; } }
function normalizeAuthSession(session) { return session?.access_token ? { ...session, expires_at: session.expires_at || Math.floor(Date.now() / 1000) + Number(session.expires_in || 3600) } : session; }
function storeAuthSession(session) { if (session?.access_token) localStorage.setItem(AUTH_STORAGE_KEY, JSON.stringify(session)); }
function clearAuthSession() { localStorage.removeItem(AUTH_STORAGE_KEY); }
function trackMeta(event, data = {}, custom = false) {
  if (typeof window.fbq !== 'function') return;
  try { window.fbq(custom ? 'trackCustom' : 'track', event, data); } catch { /* Marketing telemetry must never affect the app. */ }
}
function pixelPlanValue(plan, billing = 'monthly') {
  const prices = { starter: { monthly: 4900, annual: 46900 }, pro: { monthly: 14900, annual: 142900 }, business: { monthly: 59900, annual: 574900 } };
  return prices[plan]?.[billing] || 0;
}
async function authRequest(path, options = {}) {
  const response = await fetch(`${AUTH_CONFIG.supabaseUrl}${path}`, { ...options, headers: { apikey: AUTH_CONFIG.supabasePublishableKey, 'content-type': 'application/json', ...(options.headers || {}) } });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(payload.msg || payload.error_description || payload.message || 'Authentification impossible.');
  return payload;
}
async function refreshAuth(session) { return authRequest('/auth/v1/token?grant_type=refresh_token', { method: 'POST', body: JSON.stringify({ refresh_token: session.refresh_token }) }); }
async function hydrateAuth() {
  const hash = new URLSearchParams(window.location.hash.replace(/^#/, ''));
  let session = normalizeAuthSession(authSession());
  if (hash.get('access_token')) { session = { access_token: hash.get('access_token'), refresh_token: hash.get('refresh_token'), expires_at: Math.floor(Date.now() / 1000) + Number(hash.get('expires_in') || 3600) }; history.replaceState({}, '', window.location.pathname + window.location.search); }
  if (session?.access_token && Number(session.expires_at || 0) < Math.floor(Date.now() / 1000) + 60) { try { session = normalizeAuthSession(await refreshAuth(session)); } catch { session = null; clearAuthSession(); } }
  if (!session?.access_token) { state.authUser = null; state.sessionId = ''; state.view = 'marketing'; render(); return; }
  try {
    const user = await authRequest('/auth/v1/user', { headers: authHeaders(session.access_token) });
    storeAuthSession(normalizeAuthSession({ ...session, user })); state.authUser = user; state.sessionId = user.id; state.view = 'app'; await syncEntitlement(false); const pendingPlan = state.pendingCheckoutPlan; state.checkoutPlan = pendingPlan || null; state.pendingCheckoutPlan = null; if (pendingPlan) { state.checkoutLoading = true; await beginCheckout(); return; }
  } catch { clearAuthSession(); state.authUser = null; state.sessionId = ''; state.view = 'marketing'; }
  render();
}

function header() {
  return `<div class="promo" ${state.promo ? '' : 'style="display:none"'}>${esc(t('promo'))}<button data-action="dismiss-promo" aria-label="Fermer">×</button></div>
  <header class="topbar"><button class="logo" data-action="marketing"><img class="brand-icon" src="huggy-icon.png" alt="" aria-hidden="true"/>rowz<span>.ai</span></button><div class="top-actions"><button class="language-btn" data-action="language">${state.lang === 'fr' ? 'EN' : 'FR'}</button>${state.authUser ? `<button class="pill-btn trial" data-action="plans"><span>${state.generationCount}/${state.generationLimit} ${state.lang === 'fr' ? 'gén.' : 'gen.'}</span><span class="trial-chevron">⌄</span></button><button class="avatar" data-action="account" aria-label="Compte">${esc((state.authUser.email || 'U').slice(0, 1).toUpperCase())}</button>` : `<button class="ghost-btn" data-action="login">Connexion</button>`}</div></header>`;
}

function sidebar() {
  const q = state.search || '';
  const visible = state.files.filter(f => f.name.toLowerCase().includes(q.toLowerCase()));
  return `<aside class="sidebar"><button class="new-file" data-action="new-file">+ ${t('newFile')}</button><button class="collapse-btn" data-action="collapse" aria-label="Sidebar">${state.collapsed ? '→' : '←'}</button>${!state.collapsed ? `<input class="search" data-role="search" placeholder="${t('search')}…" value="${esc(q)}"/><div class="thread-list">${visible.length ? visible.map(f => `<button class="thread ${state.current === f.id ? 'active' : ''}" data-action="open-file" data-id="${f.id}"><span class="thread-icon">▦</span><span class="thread-copy"><strong>${esc(f.name)}</strong><small>${state.lang === 'fr' ? 'à l’instant' : 'just now'}</small></span></button>`).join('') : `<div style="padding:15px 7px;color:#8d8982;font-size:12px">${q ? (state.lang === 'fr' ? 'Aucun fil trouvé' : 'No thread found') : t('noFiles')}</div>`}</div><div class="sidebar-foot">${state.files.length} ${state.lang === 'fr' ? 'fichier' : 'file'} · ${state.generating ? (state.lang === 'fr' ? 'Génération…' : 'Generating…') : (state.lang === 'fr' ? 'Prêt' : 'Ready')}<br/>${t('fileStored')}</div>` : ''}</aside>`;
}

function composer(edit = false) {
  const value = edit ? state.editPrompt : state.prompt;
  const helper = edit ? '' : `<div class="helper">${state.lang === 'fr' ? 'Entrée pour générer · Glissez un fichier sur la console' : 'Enter to generate · Drop a file on the console'}</div>`;
  const attachment = !edit && state.attachedFile ? `<div class="attachment-chip">📎 ${esc(state.attachedFile.name)} <button data-action="remove-attachment" aria-label="Retirer">×</button></div>` : '';
  return `<div class="composer ${edit ? 'edit-composer' : ''}"><button class="clip" data-action="attach" aria-label="${state.lang === 'fr' ? 'Joindre un fichier Excel' : 'Attach an Excel file'}"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m21.44 11.05-9.19 9.19a6 6 0 0 1-8.49-8.49l9.19-9.19a4 4 0 0 1 5.66 5.66l-9.2 9.19a2 2 0 0 1-2.83-2.83l8.49-8.48"/></svg></button><textarea data-role="${edit ? 'edit-prompt' : 'prompt'}" placeholder="${edit ? t('editPlaceholder') : t('placeholder')}">${esc(value)}</textarea><button class="send" data-action="generate" aria-label="${t('generate')}" ${state.generating ? 'disabled' : ''}><svg width="17" height="17" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3.5 10h12M11 4.5 16.5 10 11 15.5"/></svg></button></div>${attachment}${helper}<input type="file" data-role="file-input" accept=".xlsx,.xls,.csv" hidden/><p class="terms">${t('terms')} <a href="#">${state.lang === 'fr' ? 'CGU' : 'Terms'}</a>.</p>`;
}

function quickActions(edit = false) {
  const items = edit
    ? [[`✨ ${t('format')}`, t('cleanPrompt')], [`📅 ${t('sort')}`, t('sortPrompt')]]
    : [[`📊 ${t('budget')}`, t('budget')], [`📉 ${t('sales')}`, t('sales')], [`📦 ${t('stock')}`, 'Crée un suivi de stock avec entrées, sorties, stock actuel et seuil d’alerte'], [`💳 ${t('cash')}`, 'Crée un cahier de caisse quotidien avec recettes, dépenses et solde'], [`✨ ${t('format')}`, t('cleanPrompt')], [`📅 ${t('sort')}`, t('sortPrompt')]];
  return `<div class="quick-actions">${items.map(([label, prompt]) => `<button class="quick" data-action="quick" data-prompt="${esc(prompt)}">${label}</button>`).join('')}</div>`;
}

function errorNotice() { return `${state.notice ? `<div class="error-notice" style="background:#edf8f0;color:#25613a;border-color:#b9ddc3">${esc(state.notice)} <button data-action="dismiss-notice">×</button></div>` : ''}${state.error ? `<div class="error-notice">${esc(state.error)} <button data-action="dismiss-error">×</button></div>` : ''}`; }
function emptyState() { return `<div class="empty-center">${errorNotice()}<h1>${t('hello')}</h1><p>${t('emptySubtitle')}</p>${composer(false)}${quickActions(false)}</div>`; }
function fileState() { const f = state.files.find(x => x.id === state.current) || state.files[0]; if (!f) return emptyState(); const stats = workbookStats(f); const validation = workbookValidation(f); return `<div class="file-view">${errorNotice()}<div class="prompt-bubble">${esc(f.prompt)}</div><div class="file-card"><div class="file-card-icon">▤</div><div class="file-card-copy"><strong>${esc(f.name)}</strong><span>v${f.version} · ${stats.sheets} feuille${stats.sheets > 1 ? 's' : ''} · ${stats.cells} cellules</span><div class="file-validation ${validation.tone}"><i>${validation.tone === 'success' ? '✓' : '!'}</i>${esc(validation.label)} · ${esc(validation.detail)}</div><div class="file-actions"><button data-action="preview">${t('preview')}</button><button data-action="download">${t('download')}</button><button data-action="history">Historique</button><button data-action="continue">${t('continue')}</button></div></div></div>${composer(true)}${quickActions(true)}<p class="context">${t('context')} : ${esc(f.name)} (v${f.version}) · ${stats.formulas} formule${stats.formulas > 1 ? 's' : ''} détectée${stats.formulas > 1 ? 's' : ''}</p></div>`; }

function generationState() { const steps = state.lang === 'fr' ? ['Analyse de votre demande…','Traitement IA en cours…','Réception du classeur…','Enregistrement du résultat…','Préparation de l’aperçu…'] : ['Analyzing your request…','AI processing…','Receiving the workbook…','Saving the result…','Preparing the preview…']; const active = Math.min(state.progress, steps.length - 1); const percent = Math.min(100, Math.max(8, Math.round((state.progress / steps.length) * 100))); return `<div class="status"><div class="status-icon">✨</div><h2>${state.lang === 'fr' ? 'Huggy construit votre fichier' : 'Huggy is building your file'}</h2><p>${state.lang === 'fr' ? 'Progression réelle du traitement en cours' : 'Live processing progress'}</p><div class="status-quote">« ${esc(state.prompt || state.editPrompt)} »</div><div class="progress-track" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${percent}"><div class="progress-fill" style="width:${percent}%"></div></div><ul class="steps">${steps.map((s,i)=>`<li class="${i < state.progress ? 'done' : i === active ? 'active' : ''}"><span class="step-dot">${i < state.progress ? '✓' : i === active ? '<i></i>' : i + 1}</span>${s}</li>`).join('')}</ul><p class="status-note">${state.lang === 'fr' ? 'Ne ferme pas cette page — ton fichier arrive.' : 'Keep this page open — your file is on the way.'}</p></div>`; }

function dashboard() { return `${header()}<div class="workspace ${state.collapsed ? 'collapsed' : ''}">${sidebar()}<main class="canvas"><div class="canvas-inner ${state.files.length && state.current ? 'has-file' : ''}">${state.generating ? generationState() : (state.files.length && state.current ? fileState() : emptyState())}</div></main></div><footer class="site-footer">© 2026 rowz.ai · ${state.lang === 'fr' ? 'Vos tableurs, en langage naturel.' : 'Your spreadsheets, in plain English.'}　·　FAQ　·　Mentions légales　·　CGU　·　Confidentialité</footer>${state.menu ? `<div class="menu profile-menu"><div class="menu-user"><div class="menu-avatar">${esc((state.authUser?.email || 'U').slice(0, 1).toUpperCase())}</div><div class="menu-email">${esc(state.authUser?.email || '')}</div></div><button data-action="account-manage">⚙　Manage account</button><button data-action="logout">↪　Sign out</button><div class="clerk-mini">Secured by <b>Huggy</b></div></div>` : ''}`; }

function landing() { return `${header()}<main class="marketing"><section class="hero"><div class="eyebrow">Excel, sans formules ni prise de tête</div><h1>L’IA qui crée et modifie vos fichiers Excel à votre place.</h1><p>Décrivez le tableau dont vous avez besoin en une phrase, ou déposez un fichier existant. Rowz s’occupe du reste.</p><button class="cta" data-action="login">Commencer gratuitement　→</button></section><section class="marketing-section"><h2>Pilotez l’IA. Regardez la magie.</h2><p>Cochez une option, le fichier se transforme instantanément.</p><div class="demo-grid"><div class="demo-panel"><h3>Panneau de contrôle IA</h3><label class="check-row"><input type="checkbox" data-demo="clean"/> 🧼 Nettoyer le fichier</label><label class="check-row"><input type="checkbox" data-demo="split"/> 📊 Répartir par catégorie</label><label class="check-row"><input type="checkbox" data-demo="theme"/> 🎨 Appliquer le thème Premium</label></div><div class="demo-sheet"><div class="sheet-title">Net mensuel : répartition</div><table class="fake-table"><thead><tr><th>Mois</th><th>Revenus</th><th>Dépenses</th><th>Net</th></tr></thead><tbody><tr><td>Janvier</td><td>3 200 €</td><td>1 140 €</td><td>+2 060 €</td></tr><tr><td>Février</td><td>2 850 €</td><td>980 €</td><td>+1 870 €</td></tr><tr><td>Total</td><td>18 550 €</td><td>5 785 €</td><td>+12 765 €</td></tr></tbody></table></div></div></section><section class="marketing-section"><h2>Un tarif simple, comme vos fichiers.</h2><p>Votre premier fichier est gratuit. Passez au niveau supérieur quand vous en avez besoin.</p><div class="pricing-grid"><div class="price-card"><h3>Starter</h3><div class="price">4,99 € <small>/mois</small></div><ul><li>40 générations par mois</li><li>Création et modification de fichiers .xlsx</li><li>Compatible Excel et Google Sheets</li></ul><button class="cta" data-action="plans">Commencer avec Starter</button></div><div class="price-card"><h3>Pro</h3><div class="price">14,99 € <small>/mois</small></div><ul><li>200 générations par mois</li><li>Tableaux de bord et formules avancées</li><li>Support prioritaire</li></ul><button class="cta" data-action="plans">Commencer avec Pro</button></div></div></section><section class="marketing-section"><h2>Questions fréquentes</h2><div class="faq"><details open><summary>Et si le fichier ne correspond pas à ce que je voulais ?</summary><p>Reformulez votre demande et Rowz régénère le fichier.</p></details><details><summary>Est-ce que je dois savoir utiliser Excel ?</summary><p>Non. Vous décrivez ce dont vous avez besoin en une phrase.</p></details><details><summary>Puis-je modifier un fichier que j’ai déjà ?</summary><p>Oui, joignez votre fichier et demandez une modification précise.</p></details></div></section></main><footer class="site-footer">© 2026 rowz.ai · Vos tableurs, en langage naturel.</footer>${state.modal ? modal() : ''}`; }

function landingMinimal() {
  return `${header()}<main class="marketing-minimal">
    <section class="minimal-hero">
      <div class="minimal-hero-copy">
        <div class="minimal-eyebrow">HUGGY EXCEL <span>·</span> TON ASSISTANT TABLEUR</div>
        <h1>Des tableurs clairs,<br/><em>sans formules.</em></h1>
        <p>Décris ce dont tu as besoin en quelques mots. Huggy crée un fichier Excel structuré, utile et prêt à télécharger.</p>
        <div class="minimal-actions"><button class="minimal-cta" data-action="login">Commencer gratuitement <span>→</span></button><a class="minimal-secondary" href="#how-it-works">Voir comment ça marche <span>↓</span></a></div>
        <div class="minimal-trust"><span>✦ 1 génération offerte</span><span>Pas de carte bancaire</span><span>Export Excel</span></div>
      </div>
      <div class="minimal-product" aria-label="Aperçu d’un fichier créé par Huggy">
        <div class="minimal-prompt"><span class="minimal-spark">✦</span><span>Crée un suivi des ventes mensuelles avec un tableau de bord</span><span class="minimal-arrow">↗</span></div>
        <div class="minimal-sheet"><div class="minimal-sheet-head"><span></span><span></span><span></span></div><div class="minimal-sheet-title">Suivi des ventes <b>·</b> Avril 2026 <small>Généré par Huggy</small></div><div class="minimal-sheet-grid"><i>Produit</i><i>Ventes</i><i>Chiffre d’affaires</i><i>Casque audio</i><i>48</i><i>2 390 000 FCFA</i><i>Clavier mécanique</i><i>32</i><i>1 760 000 FCFA</i><i>Souris ergonomique</i><i>27</i><i>945 000 FCFA</i></div><div class="minimal-sheet-foot"><span><b>✓</b> Tableau prêt</span><span>.xlsx</span></div></div>
      </div>
    </section>
    <section class="minimal-proof" aria-label="Avantages Huggy"><div><strong>1 phrase</strong><span>pour commencer</span></div><div><strong>Excel</strong><span>créé et modifié</span></div><div><strong>100%</strong><span>en français</span></div></section>
    <section class="minimal-section" id="how-it-works"><div class="minimal-section-head"><span class="minimal-section-kicker">SIMPLE PAR DESIGN</span><h2>Ton idée devient un fichier<br/><em>en trois étapes.</em></h2><p>Aucune formule à mémoriser. Tu expliques, Huggy organise.</p></div><div class="minimal-steps"><article><span class="step-number">01</span><div class="step-icon">✎</div><h3>Décris</h3><p>Écris ton besoin comme tu le dirais à un collègue.</p></article><article><span class="step-number">02</span><div class="step-icon">✦</div><h3>Génère</h3><p>Huggy structure les données, les formules et la mise en forme.</p></article><article><span class="step-number">03</span><div class="step-icon">↓</div><h3>Télécharge</h3><p>Prévisualise ton résultat puis récupère ton fichier Excel.</p></article></div></section>
    <section class="minimal-use-cases"><div><span class="minimal-section-kicker">POUR TON QUOTIDIEN</span><h2>Un fichier utile,<br/><em>pas un fichier compliqué.</em></h2></div><div class="use-case-list"><span>Suivi des ventes <b>↗</b></span><span>Budget et trésorerie <b>↗</b></span><span>Tableau de bord <b>↗</b></span><span>Nettoyage de données <b>↗</b></span></div></section>
    <section class="minimal-final-cta"><span class="minimal-section-kicker">PRÊT À COMMENCER ?</span><h2>Ton prochain tableau<br/><em>commence ici.</em></h2><button class="minimal-cta" data-action="login">Créer mon premier fichier <span>→</span></button><small>1 génération offerte · aucune carte bancaire</small></section>
  </main><footer class="site-footer">© 2026 Huggy · Tes tableurs, en langage naturel.</footer>${state.modal ? modal() : ''}`;
}

function workbookSheets(file) {
  const source = Array.isArray(file?.workbook?.sheets) ? file.workbook.sheets : [];
  return source.map((sheet, index) => {
    const rows = Array.isArray(sheet?.rows) ? sheet.rows.filter(Array.isArray).map(row => row.map(value => value ?? '')) : [];
    const columns = Array.isArray(sheet?.columns) ? sheet.columns.map(value => value ?? '') : [];
    if (!rows.length && columns.length) rows.push(columns);
    return { id: `sheet-${index}`, name: String(sheet?.name || `Feuille ${index + 1}`), rows };
  }).filter(sheet => sheet.rows.length);
}
function workbookStats(file) { const sheets = workbookSheets(file); const rows = sheets.reduce((total, sheet) => total + sheet.rows.length, 0); const cells = sheets.reduce((total, sheet) => total + sheet.rows.reduce((count, row) => count + row.length, 0), 0); const formulas = sheets.reduce((total, sheet) => total + sheet.rows.flat().filter(value => typeof value === 'string' && value.trim().startsWith('=')).length, 0) + (Array.isArray(file?.workbook?.formulas) ? file.workbook.formulas.length : 0); const warnings = sheets.filter(sheet => sheet.rows.length < 2).map(sheet => `${sheet.name} ne contient que les en-têtes.`); return { sheets: sheets.length, rows, cells, formulas, warnings }; }
function workbookValidation(file) { const stats = workbookStats(file); if (!stats.sheets) return { label: 'À vérifier', tone: 'warning', detail: 'Aucune feuille exploitable.' }; if (stats.warnings.length) return { label: 'À vérifier', tone: 'warning', detail: stats.warnings.join(' ') }; return { label: 'Classeur valide', tone: 'success', detail: `${stats.sheets} feuille${stats.sheets > 1 ? 's' : ''}, ${stats.rows} lignes et ${stats.formulas} formule${stats.formulas > 1 ? 's' : ''}.` }; }
function columnLabel(index) { let label = ''; for (let value = index + 1; value > 0; value = Math.floor((value - 1) / 26)) label = String.fromCharCode(65 + ((value - 1) % 26)) + label; return label; }
function xmlEsc(value) { return String(value ?? '').replace(/[<>&"']/g, char => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', '"': '&quot;', "'": '&apos;' }[char])); }
function excelSheetName(value, index, used) {
  const base = String(value || `Feuille ${index + 1}`).replace(/[\\/?*\[\]:]/g, ' ').trim().slice(0, 31) || `Feuille ${index + 1}`;
  let name = base; let suffix = 2;
  while (used.has(name.toLowerCase())) { const tail = ` ${suffix++}`; name = `${base.slice(0, 31 - tail.length)}${tail}`; }
  used.add(name.toLowerCase()); return name;
}
function excelCell(value, header = false) {
  const numeric = typeof value === 'number' && Number.isFinite(value);
  const boolean = typeof value === 'boolean';
  const type = numeric ? 'Number' : boolean ? 'Boolean' : 'String';
  const content = boolean ? (value ? 1 : 0) : value;
  return `<Cell${header ? ' ss:StyleID="Header"' : ''}><Data ss:Type="${type}">${xmlEsc(content)}</Data></Cell>`;
}
function downloadWorkbook() {
  const file = state.files.find(item => item.id === state.current) || state.files[0]; if (!file) return;
  const sheets = workbookSheets(file); if (!sheets.length) { state.error = 'Ce classeur ne contient aucune feuille exportable.'; render(); return; }
  const usedNames = new Set();
  const worksheets = sheets.map((sheet, index) => `<Worksheet ss:Name="${xmlEsc(excelSheetName(sheet.name, index, usedNames))}"><Table>${sheet.rows.map((row, rowIndex) => `<Row>${row.map(value => excelCell(value, rowIndex === 0)).join('')}</Row>`).join('')}</Table></Worksheet>`).join('');
  const xml = `<?xml version="1.0" encoding="UTF-8"?><?mso-application progid="Excel.Sheet"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Styles><Style ss:ID="Default" ss:Name="Normal"><Alignment ss:Vertical="Bottom"/><Font ss:FontName="Calibri" ss:Size="11"/></Style><Style ss:ID="Header"><Font ss:FontName="Calibri" ss:Size="11" ss:Bold="1"/><Interior ss:Color="#F2E7DF" ss:Pattern="Solid"/></Style></Styles>${worksheets}</Workbook>`;
  const blob = new Blob([xml], { type: 'application/vnd.ms-excel;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = file.name.replace(/\.xlsx?$/i, '.xls'); link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000);
}
function previewModal() {
  const file = state.files.find(item => item.id === state.current) || state.files[0];
  const sheets = workbookSheets(file); const activeSheet = sheets.find(sheet => sheet.id === state.sheet) || sheets[0];
  if (!file || !activeSheet) return `<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h2>Aperçu indisponible</h2><button class="modal-close" data-action="close-modal">×</button></div><div class="modal-body"><p>Le moteur IA n’a renvoyé aucune feuille exploitable.</p></div></div></div>`;
  const width = Math.max(1, ...activeSheet.rows.map(row => row.length));
  const summary = file.workbook?.summary ? `<div class="preview-banner">${esc(file.workbook.summary)}</div>` : '';
  const notes = Array.isArray(file.workbook?.notes) && file.workbook.notes.length ? `<details class="workbook-notes"><summary>Hypothèses et conseils (${file.workbook.notes.length})</summary><ul>${file.workbook.notes.map(note => `<li>${esc(note)}</li>`).join('')}</ul></details>` : '';
  const validation = workbookValidation(file); const stats = workbookStats(file);
  return `<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h2>${t('preview')} de ${esc(file.name)}</h2><button class="modal-close" data-action="close-modal">×</button></div><div class="modal-body"><div class="sheet-tabs">${sheets.map(sheet => `<button class="${sheet.id === activeSheet.id ? 'active' : ''}" data-action="sheet" data-sheet="${sheet.id}">${esc(sheet.name)}</button>`).join('')}</div>${summary}<div class="validation-card ${validation.tone}"><span class="validation-icon">${validation.tone === 'success' ? '✓' : '!'}</span><div><strong>${validation.label}</strong><span>${esc(validation.detail)}</span></div><small>${stats.cells} cellules analysées</small></div><div class="grid-wrap"><table class="grid-table"><thead><tr><th class="row-number"></th>${Array.from({ length: width }, (_, index) => `<th>${columnLabel(index)}</th>`).join('')}</tr></thead><tbody>${activeSheet.rows.map((row, rowIndex) => `<tr><td class="row-number">${rowIndex + 1}</td>${Array.from({ length: width }, (_, columnIndex) => `<td>${esc(row[columnIndex] ?? '')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${notes}<p class="preview-meta">${sheets.length} feuille${sheets.length > 1 ? 's' : ''} générée${sheets.length > 1 ? 's' : ''} pour ta demande · données réelles du résultat IA</p></div></div></div>`;
}
function historyModal() { const file = state.files.find(item => item.id === state.current) || state.files[0]; const history = [...(file?.history || [])].sort((a, b) => Number(b.version || 0) - Number(a.version || 0)); return `<div class="modal-backdrop"><div class="modal history-modal"><div class="modal-head"><div><span class="auth-kicker">CLASSEUR</span><h2>Historique des versions</h2></div><button class="modal-close" data-action="close-modal">×</button></div><div class="modal-body"><p class="history-intro">Retrouve les versions précédentes de <strong>${esc(file?.name || '')}</strong>. Une restauration crée toujours une nouvelle version.</p><div class="history-list">${history.map(item => `<div class="history-row ${Number(item.version) === Number(file?.version) ? 'current' : ''}"><div class="history-version"><span>v${Number(item.version || 1)}</span><small>${item.createdAt ? new Date(item.createdAt).toLocaleString('fr-FR', { dateStyle: 'medium', timeStyle: 'short' }) : 'Version enregistrée'}</small></div><div class="history-prompt">${esc(item.prompt || 'Version initiale')}</div>${Number(item.version) === Number(file?.version) ? '<b class="history-current">Actuelle</b>' : `<button class="outline-button small" data-action="restore-version" data-version="${Number(item.version)}">Restaurer</button>`}</div>`).join('')}</div></div></div></div>`; }
function restoreVersion(version) { const file = state.files.find(item => item.id === state.current) || state.files[0]; const target = file?.history?.find(item => Number(item.version) === Number(version)); if (!file || !target) return; const nextVersion = Number(file.version || 1) + 1; const restored = { ...file, version: nextVersion, prompt: `Restauration de la version ${version}`, workbook: JSON.parse(JSON.stringify(target.workbook)), history: [...(file.history || []), { version: nextVersion, prompt: `Restauration de la version ${version}`, workbook: JSON.parse(JSON.stringify(target.workbook)), createdAt: new Date().toISOString() }] }; state.files = state.files.map(item => item.id === file.id ? restored : item); state.modal = null; state.notice = `Version ${version} restaurée dans une nouvelle version ${nextVersion}.`; save(); render(); }
function accountModal() {
  const profile = state.accountTab === 'profile';
  return `<div class="modal-backdrop account-backdrop"><div class="modal account-modal"><div class="account-layout"><aside class="account-side"><h2>Account</h2><p>Manage your account info.</p><button class="account-tab ${profile ? 'active' : ''}" data-action="account-tab" data-tab="profile">◉　Profile</button><button class="account-tab ${!profile ? 'active' : ''}" data-action="account-tab" data-tab="security">♢　Security</button></aside><section class="account-content"><button class="account-x" data-action="close-modal">×</button>${profile ? profileAccountPanel() : securityAccountPanel()}</section></div><div class="clerk-footer">Secured by <b>Supabase</b></div></div></div>`;
}

function profileAccountPanel() {
  const metadata = state.authUser?.user_metadata || {};
  const initial = esc((state.authUser?.email || 'U').slice(0, 1).toUpperCase());
  return `<h1>Profile details</h1><div class="account-rule"></div><div class="account-label">Profile</div>${state.accountEdit === 'profile' ? `<div class="inline-account-card"><h3>Update profile</h3><div class="avatar-upload"><div class="account-avatar">${initial}</div><div><p>Ces informations sont utilisées pour ouvrir directement le checkout Chariow.</p></div></div><div class="profile-fields"><label>Prénom<input data-role="profile-first-name" placeholder="Prénom" value="${esc(metadata.first_name || metadata.firstName || '')}" /></label><label>Nom<input data-role="profile-last-name" placeholder="Nom" value="${esc(metadata.last_name || metadata.lastName || '')}" /></label><label>Téléphone<input type="tel" data-role="profile-phone" placeholder="0700000000" value="${esc(metadata.phone || '')}" /></label><label>Code pays<input data-role="profile-country" maxlength="2" value="${esc(metadata.country_code || 'CI')}" /></label></div><div class="inline-actions"><button data-action="cancel-account-edit">Annuler</button><button data-action="save-profile">Enregistrer</button></div></div>` : `<div class="profile-row"><div class="account-avatar">${initial}</div><button class="link-action" data-action="update-profile">Modifier le profil</button></div>`}<div class="account-rule"></div><div class="account-label">Email address</div><div class="email-row"><span>${esc(state.authUser?.email || '')}</span><span class="primary-badge">Primary</span></div><div class="account-rule"></div><div class="account-label">Connected accounts</div><span class="account-muted">Supabase Auth actif</span>`;
}

function securityAccountPanel() {
  return `<h1>Security</h1><div class="account-rule"></div>${state.accountEdit === 'password' ? `<div class="inline-account-card"><h3>Update password</h3><label>New password<input type="password" /></label><label>Confirm password<input type="password" /></label><label class="device-check"><input type="checkbox" checked /> <span>Sign out of all other devices<small>It is recommended to sign out of all other devices which may have used your old password.</small></span></label><div class="inline-actions"><button data-action="cancel-account-edit">Cancel</button><button class="save-disabled" disabled>Save</button></div></div>` : `<div class="security-row"><div><div class="account-label">Password</div><div class="masked">••••••••••</div></div><button class="link-action" data-action="update-password">Update password</button></div>`}<div class="account-rule"></div><div class="account-label">Active session</div><div class="device-row"><span class="device-icon">▰</span><div><b>Navigateur actuel</b><span class="device-badge">Session active</span><small>Cette session est protégée par Supabase Auth.</small></div></div><div class="account-rule"></div><div class="account-label">Delete account</div><button class="danger-link" data-action="delete-account">Delete account</button>`;
}

function authModal() { const signup = state.authMode === 'signup'; return `<div class="modal-backdrop auth-backdrop"><div class="modal auth-modal"><div class="auth-topline"><span class="auth-mark">✦</span><span>Huggy Excel</span></div><div class="modal-head"><div><span class="auth-kicker">${signup ? 'NOUVEAU COMPTE' : 'BIENVENUE'}</span><h2>${signup ? 'Créer ton compte' : 'Bon retour'}</h2></div><button class="modal-close" data-action="close-modal" aria-label="Fermer">×</button></div><div class="modal-body"><p class="auth-intro">${signup ? 'Un espace simple pour créer, modifier et retrouver tes classeurs.' : 'Connecte-toi pour retrouver tes générations et continuer ton travail.'}</p><button class="google-button" type="button" data-action="google-login"><span class="google-g">G</span><span>Continuer avec Google</span></button><div class="auth-divider"><span>ou avec ton email</span></div><form data-role="auth-form">${signup ? `<label>Prénom<input data-role="auth-first-name" autocomplete="given-name" required /></label><label>Nom<input data-role="auth-last-name" autocomplete="family-name" required /></label><label>Téléphone<input type="tel" data-role="auth-phone" autocomplete="tel" placeholder="0700000000" required /></label><label>Code pays<input data-role="auth-country" value="CI" maxlength="2" required /></label>` : ''}<label>Email<input type="email" data-role="auth-email" autocomplete="email" required /></label><label>Mot de passe<input type="password" data-role="auth-password" autocomplete="${signup ? 'new-password' : 'current-password'}" minlength="8" required /></label><button class="checkout-submit" type="submit" ${state.authLoading ? 'disabled' : ''}>${state.authLoading ? 'Patiente…' : (signup ? 'Créer mon compte' : 'Se connecter')}</button></form>${state.authError ? `<p class="checkout-error">${esc(state.authError)}</p>` : ''}${state.authMessage ? `<p class="auth-message">${esc(state.authMessage)}</p>` : ''}<button class="back-link auth-switch" data-action="auth-switch">${signup ? 'J’ai déjà un compte' : 'Créer un compte'}</button></div><div class="auth-footer">Accès sécurisé · Tes données restent privées</div></div></div>`; }
function modal() { return state.modal === 'preview' ? previewModal() : state.modal === 'history' ? historyModal() : state.modal === 'account' ? accountModal() : state.modal === 'auth' ? authModal() : paywall(); }

function checkoutForm() { const plan = state.checkoutPlan === 'business' ? 'Business' : state.checkoutPlan === 'pro' ? 'Pro' : 'Starter'; const total = state.billing === 'annual' ? (state.checkoutPlan === 'business' ? '574 900' : state.checkoutPlan === 'pro' ? '142 900' : '46 900') : (state.checkoutPlan === 'business' ? '59 900' : state.checkoutPlan === 'pro' ? '14 900' : '4 900'); const metadata = state.authUser?.user_metadata || {}; const email = state.authUser?.email || ''; return `<div class="checkout-form"><button class="back-link" data-action="back-plans">← Retour aux plans</button><h3>Activer ${plan}</h3><p>Paiement sécurisé par Chariow · ${total} FCFA ${state.billing === 'annual' ? 'pour 12 mois' : 'pour 30 jours'}</p><p class="checkout-hint">Après validation, tu seras redirigé directement vers le checkout Chariow.</p><label>Prénom<input data-role="checkout-first-name" autocomplete="given-name" value="${esc(metadata.first_name || metadata.firstName || '')}" required /></label><label>Nom<input data-role="checkout-last-name" autocomplete="family-name" value="${esc(metadata.last_name || metadata.lastName || '')}" required /></label><label>Email<input type="email" data-role="checkout-email" autocomplete="email" value="${esc(email)}" required /></label><label>Téléphone<input type="tel" data-role="checkout-phone" placeholder="0700000000" value="${esc(metadata.phone || '')}" required /></label><label>Code pays<input data-role="checkout-country" value="${esc(metadata.country_code || 'CI')}" maxlength="2" required /></label><button class="checkout-submit" data-action="checkout-submit" ${state.checkoutLoading ? 'disabled' : ''}>${state.checkoutLoading ? 'Préparation…' : 'Payer avec Chariow →'}</button>${state.error ? `<p class="checkout-error">${esc(state.error)}</p>` : ''}</div>`; }

function paywallWithForm() { if (state.checkoutPlan) return `<div class="modal-backdrop"><div class="modal paywall"><div class="modal-head"><h2>Choisis ton plan Huggy Excel</h2><button class="modal-close" data-action="close-modal">×</button></div><div class="modal-body">${checkoutForm()}</div></div></div>`; const annual = state.billing === 'annual'; return `<div class="modal-backdrop"><div class="modal paywall"><div class="modal-head"><h2>Choisis ton plan Huggy Excel</h2><button class="modal-close" data-action="close-modal">×</button></div><div class="modal-body"><p class="paywall-intro">Une génération gratuite est incluse. Les plans payants débloquent plus de générations et davantage de capacité.</p><div class="billing"><button class="${!annual ? 'active' : ''}" data-action="billing" data-billing="monthly">Mensuel</button><button class="${annual ? 'active' : ''}" data-action="billing" data-billing="annual">Annuel</button><span style="color:var(--terracotta-deep);font-size:12px;padding:8px">≈ -20%</span></div><div class="paywall-cards"><div class="pay-card"><h3>Starter</h3><div class="pay-price">${annual ? '46 900 FCFA' : '4 900 FCFA'} <small>${annual ? '/an' : '/mois'}</small></div><p>50 générations par mois</p><ul><li>Création de classeurs</li><li>Création et modification Excel</li><li>Exports CSV/XLSX</li></ul><button data-action="start-checkout" data-plan="starter">Choisir Starter</button></div><div class="pay-card popular"><h3>Pro</h3><div class="pay-price">${annual ? '142 900 FCFA' : '14 900 FCFA'} <small>${annual ? '/an' : '/mois'}</small></div><p>250 générations par mois</p><ul><li>Générations avancées</li><li>Tableaux de bord complets</li><li>Traitement prioritaire</li></ul><button data-action="start-checkout" data-plan="pro">Choisir Pro</button></div><div class="pay-card"><h3>Business</h3><div class="pay-price">${annual ? '574 900 FCFA' : '59 900 FCFA'} <small>${annual ? '/an' : '/mois'}</small></div><p>1 000 générations par mois</p><ul><li>Générations haute capacité</li><li>Espaces partagés</li><li>Support prioritaire</li></ul><button data-action="start-checkout" data-plan="business">Choisir Business</button></div></div><p style="color:var(--soft);font-size:11px;margin-bottom:0">Accès ${annual ? '12 mois' : '30 jours'} activé automatiquement après paiement ; renouvellement manuel sécurisé par Chariow.</p></div></div></div>`; }

function paywall() { const annual = state.billing === 'annual'; return `<div class="modal-backdrop"><div class="modal paywall"><div class="modal-head"><h2>Choisis ton plan Huggy Excel</h2><button class="modal-close" data-action="close-modal">×</button></div><div class="modal-body"><p class="paywall-intro">Une génération gratuite est incluse. Choisis un plan et tu seras envoyé directement vers le checkout Chariow.</p><div class="billing"><button class="${!annual ? 'active' : ''}" data-action="billing" data-billing="monthly">Mensuel</button><button class="${annual ? 'active' : ''}" data-action="billing" data-billing="annual">Annuel</button><span style="color:var(--terracotta-deep);font-size:12px;padding:8px">≈ -20%</span></div><div class="paywall-cards"><div class="pay-card"><h3>Starter</h3><div class="pay-price">${annual ? '46 900 FCFA' : '4 900 FCFA'} <small>${annual ? '/an' : '/mois'}</small></div><p>50 générations par mois</p><ul><li>Création de classeurs</li><li>Création et modification Excel</li><li>Exports CSV/XLSX</li></ul><button data-action="start-checkout" data-plan="starter">Payer avec Chariow →</button></div><div class="pay-card popular"><h3>Pro</h3><div class="pay-price">${annual ? '142 900 FCFA' : '14 900 FCFA'} <small>${annual ? '/an' : '/mois'}</small></div><p>250 générations par mois</p><ul><li>Générations avancées</li><li>Tableaux de bord complets</li><li>Traitement prioritaire</li></ul><button data-action="start-checkout" data-plan="pro">Payer avec Chariow →</button></div><div class="pay-card"><h3>Business</h3><div class="pay-price">${annual ? '574 900 FCFA' : '59 900 FCFA'} <small>${annual ? '/an' : '/mois'}</small></div><p>1 000 générations par mois</p><ul><li>Générations haute capacité</li><li>Espaces partagés</li><li>Support prioritaire</li></ul><button data-action="start-checkout" data-plan="business">Payer avec Chariow →</button></div></div><p style="color:var(--soft);font-size:11px;margin-bottom:0">Le checkout Chariow recueille les coordonnées de paiement et confirme automatiquement ton abonnement.</p></div></div></div>`; }

function landingV2() { return `${header()}<main class="marketing"><section class="hero"><div class="eyebrow">Excel, sans formules ni prise de tête</div><h1>L’IA qui crée et modifie tes fichiers Excel.</h1><p>Décris le tableau dont tu as besoin en une phrase, ou joins un fichier existant. Huggy Excel s’occupe du reste.</p><button class="cta" data-action="login">Commencer gratuitement　→</button></section><section class="marketing-section"><h2>Pilote l’IA. Regarde la magie.</h2><p>Une génération gratuite pour découvrir Huggy Excel, puis des plans adaptés à ton volume.</p><div class="pricing-grid"><div class="price-card"><h3>Starter</h3><div class="price">4 900 FCFA <small>/mois</small></div><ul><li>50 générations</li><li>Création et modification Excel</li><li>Exports CSV/XLSX</li></ul><button class="cta" data-action="plans" data-plan="starter">Choisir Starter</button></div><div class="price-card"><h3>Pro</h3><div class="price">14 900 FCFA <small>/mois</small></div><ul><li>250 générations</li><li>Tableaux de bord avancés</li><li>Traitement prioritaire</li></ul><button class="cta" data-action="plans" data-plan="pro">Choisir Pro</button></div><div class="price-card"><h3>Business</h3><div class="price">59 900 FCFA <small>/mois</small></div><ul><li>1 000 générations</li><li>Traitement haute capacité</li><li>Espaces partagés</li></ul><button class="cta" data-action="plans" data-plan="business">Choisir Business</button></div></div></section><section class="marketing-section"><h2>Questions fréquentes</h2><div class="faq"><details open><summary>Comment fonctionne la génération ?</summary><p>Huggy analyse ta demande et prépare un classeur structuré adapté à ton besoin.</p></details><details><summary>Puis-je modifier un fichier existant ?</summary><p>Oui, joins ton fichier Excel puis décris précisément la modification à effectuer.</p></details></div></section></main><footer class="site-footer">© 2026 Huggy Excel · Tes tableurs, en langage naturel.</footer>${state.modal ? modal() : ''}`; }

function brand(html) { return html.replaceAll('rowz<span>.ai</span>', 'Huggy').replaceAll('rowz.ai', 'Huggy').replaceAll('Rowz', 'Huggy').replaceAll('rowz.local', 'huggy.local'); }
function render() { app.innerHTML = brand(state.view === 'marketing' ? landingMinimal() : dashboard() + (state.modal ? modal() : '')); }
async function startGeneration() {
  const prompt = (state.prompt || state.editPrompt || '').trim();
  if (!prompt || state.generating) return;
  if (!state.authUser) { state.modal = 'auth'; state.authMode = 'login'; render(); return; }
  if (state.generationCount >= state.generationLimit) { state.modal = 'paywall'; render(); return; }
  const currentFile = state.files.find(file => file.id === state.current) || null;
  const editing = Boolean(currentFile && state.editPrompt.trim());
  const baseWorkbook = editing ? currentFile.workbook : null;
  state.generating = true; state.progress = 0; state.error = ''; state.notice = ''; render();
  try {
    const response = await fetch('/api/generate', { method: 'POST', headers: { Accept: 'text/event-stream', 'Content-Type': 'application/json', ...authHeaders() }, body: JSON.stringify({ prompt, fileName: state.attachedFile?.name || '', fileText: state.attachedFile?.text || '', baseWorkbook }) });
    if (!response.ok) { const payload = await response.json().catch(() => ({})); const error = new Error(payload.error || 'La génération a échoué.'); error.status = response.status; throw error; }
    if (!response.body) throw new Error('Le flux de progression est indisponible.');
    const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ''; let payload = null;
    const consume = async block => { let event = 'message'; let data = ''; for (const line of block.split(/\r?\n/)) { if (line.startsWith('event:')) event = line.slice(6).trim(); if (line.startsWith('data:')) data += line.slice(5).trim(); } if (!data) return; const parsed = JSON.parse(data); if (event === 'stage') { const nextProgress = Math.max(state.progress, Math.min(4, Number(parsed.stage || 1) - 1)); if (nextProgress !== state.progress || Number(parsed.stage) === 1) { state.progress = nextProgress; render(); await new Promise(resolve => setTimeout(resolve, 450)); } } if (event === 'complete') payload = parsed; if (event === 'error') { const error = new Error(parsed.error || 'La génération a échoué.'); error.status = parsed.status; throw error; } };
    while (true) { const { value, done } = await reader.read(); buffer += decoder.decode(value || new Uint8Array(), { stream: !done }); const chunks = buffer.split(/\r?\n\r?\n/); buffer = chunks.pop() || ''; for (const chunk of chunks) await consume(chunk); if (done) break; }
    if (buffer.trim()) await consume(buffer);
    if (!payload) throw new Error('La génération n’a pas renvoyé de résultat.');
    state.progress = 5; render();
    await new Promise(resolve => setTimeout(resolve, 260));
    const id = editing ? currentFile.id : crypto.randomUUID();
    const title = payload.workbook?.title || 'classeur-ia';
    const nextVersion = editing ? Number(currentFile.version || 1) + 1 : 1;
    const versionEntry = { version: nextVersion, prompt, workbook: payload.workbook, createdAt: new Date().toISOString() };
    const file = editing ? { ...currentFile, prompt, version: nextVersion, workbook: payload.workbook, history: [...(currentFile.history || []), versionEntry] } : { id, name: `${title.toLowerCase().replace(/[^a-z0-9]+/gi, '-').replace(/^-|-$/g, '') || 'classeur-ia'}.xlsx`, prompt, version: 1, workbook: payload.workbook, history: [versionEntry] };
    state.sheet = workbookSheets(file)[0]?.id || '';
    trackMeta('HuggyGeneration', { plan: payload.account?.plan || state.plan, has_attachment: Boolean(state.attachedFile) }, true);
    state.files = editing ? state.files.map(item => item.id === id ? file : item) : [...state.files.filter(f => f.id !== id), file]; state.current = id; state.plan = payload.account?.plan || state.plan; state.generationLimit = payload.account?.generationLimit || state.generationLimit; state.generationCount = payload.account?.used ?? (state.generationCount + 1); state.trialUsed = state.generationCount >= state.generationLimit; state.generating = false; state.prompt = ''; state.editPrompt = ''; state.attachedFile = null; state.notice = editing ? `Version ${nextVersion} enregistrée. Tu peux continuer à la modifier.` : 'Classeur généré et validé. Tu peux le prévisualiser, le modifier ou le télécharger.'; save(); render();
  } catch (error) {
    state.generating = false; state.error = error.message || 'Une erreur est survenue.'; if (error.status === 429) state.modal = 'paywall'; render();
  }
}

async function syncEntitlement(showCheckoutNotice = false) {
  if (!state.authUser) return false;
  try {
    const response = await fetch('/api/account', { headers: { accept: 'application/json', ...authHeaders() } });
    if (!response.ok) return false;
    const account = await response.json();
    state.plan = account.plan || 'free'; state.generationLimit = account.generationLimit || 1; state.generationCount = account.used || 0; state.trialUsed = state.generationCount >= state.generationLimit;
    if (showCheckoutNotice) {
      state.notice = account.status === 'active' ? `Paiement confirmé : le plan ${account.planName} est actif.` : 'Paiement reçu. L’activation automatique est en cours.';
      if (account.status === 'active' && sessionStorage.getItem('huggy-purchase-tracked') !== '1') {
        trackMeta('Purchase', { content_name: account.plan || state.plan, value: pixelPlanValue(account.plan || state.plan, account.billingCycle || state.billing), currency: 'XOF' });
        sessionStorage.setItem('huggy-purchase-tracked', '1');
      }
    }
    save(); render();
    return account.status === 'active';
  } catch { return false; }
}

app.addEventListener('input', e => { if (e.target.matches('[data-role="search"]')) { state.search = e.target.value; render(); } if (e.target.matches('[data-role="prompt"]')) state.prompt = e.target.value; if (e.target.matches('[data-role="edit-prompt"]')) state.editPrompt = e.target.value; });
app.addEventListener('change', async e => { if (!e.target.matches('[data-role="file-input"]') || !e.target.files?.[0]) return; const file = e.target.files[0]; const allowed = /\.(xlsx|xls|csv)$/i.test(file.name); if (!allowed) { state.error = 'Formats acceptés : .xlsx, .xls ou .csv.'; render(); return; } if (file.size > 5 * 1024 * 1024) { state.error = 'Le fichier doit faire moins de 5 Mo.'; render(); return; } let text = ''; if (/\.csv$/i.test(file.name)) text = (await file.text()).slice(0, 12000); state.attachedFile = { name: file.name, size: file.size, type: file.type, text }; if (!state.prompt) state.prompt = `Analyse et transforme le fichier ${file.name}`; state.error = ''; render(); });
async function beginAuth() { const authMode = state.authMode; const value = role => document.querySelector(`[data-role="${role}"]`)?.value.trim() || ''; const email = value('auth-email').toLowerCase(); const password = document.querySelector('[data-role="auth-password"]')?.value || ''; const firstName = value('auth-first-name'); const lastName = value('auth-last-name'); const phone = value('auth-phone'); const countryCode = value('auth-country').toUpperCase() || 'CI'; state.authLoading = true; state.authError = ''; state.authMessage = ''; render(); try { const payload = authMode === 'signup' ? await authRequest('/auth/v1/signup', { method: 'POST', body: JSON.stringify({ email, password, options: { email_redirect_to: window.location.origin + '/', data: { first_name: firstName, last_name: lastName, phone, country_code: countryCode } } }) }) : await authRequest('/auth/v1/token?grant_type=password', { method: 'POST', body: JSON.stringify({ email, password }) }); if (!payload.access_token) { state.authLoading = false; state.authMessage = 'Compte créé. Vérifie ton email pour confirmer ton adresse, puis connecte-toi.'; render(); return; } const session = normalizeAuthSession(payload); storeAuthSession(session); state.authUser = session.user; state.sessionId = session.user.id; state.view = 'app'; if (authMode === 'signup') trackMeta('CompleteRegistration', { status: 'completed', method: 'email' }); const pendingPlan = state.pendingCheckoutPlan; state.checkoutPlan = pendingPlan || null; state.pendingCheckoutPlan = null; state.modal = null; state.authLoading = false; await syncEntitlement(false); if (pendingPlan) { state.checkoutLoading = true; await beginCheckout(); } else render(); } catch (error) { state.authLoading = false; state.authError = error.message || 'Authentification impossible.'; render(); } }
async function signOut() { const session = authSession(); if (session?.access_token) await authRequest('/auth/v1/logout', { method: 'POST', headers: authHeaders(session.access_token) }).catch(() => {}); clearAuthSession(); state.authUser = null; state.sessionId = ''; state.view = 'marketing'; state.modal = null; state.menu = false; state.files = []; state.current = null; state.plan = 'free'; state.generationCount = 0; state.generationLimit = 1; save(); render(); }
async function saveProfile() { const value = role => document.querySelector(`[data-role="${role}"]`)?.value.trim() || ''; const firstName = value('profile-first-name'); const lastName = value('profile-last-name'); const phone = value('profile-phone'); const countryCode = value('profile-country').toUpperCase() || 'CI'; if (!firstName || !lastName || phone.replace(/\D/g, '').length < 6 || !/^[A-Z]{2}$/.test(countryCode)) { state.error = 'Renseigne un prénom, un nom, un téléphone et un code pays valide.'; render(); return; } try { const session = authSession(); const current = state.authUser?.user_metadata || {}; const user = await authRequest('/auth/v1/user', { method: 'PUT', headers: authHeaders(session?.access_token), body: JSON.stringify({ data: { ...current, first_name: firstName, last_name: lastName, phone, country_code: countryCode } }) }); state.authUser = user; storeAuthSession(normalizeAuthSession({ ...session, user })); state.accountEdit = null; state.notice = 'Profil enregistré. Les prochains paiements ouvriront directement le checkout Chariow.'; state.error = ''; render(); } catch (error) { state.error = error.message || 'Impossible d’enregistrer le profil.'; render(); } }
function signInWithGoogle() { trackMeta('Login', { method: 'google' }); const redirectTo = `${window.location.origin}/`; const authorize = new URL('/auth/v1/authorize', AUTH_CONFIG.supabaseUrl); authorize.searchParams.set('provider', 'google'); authorize.searchParams.set('redirect_to', redirectTo); window.location.assign(authorize.toString()); }
app.addEventListener('click', e => { const el = e.target.closest('[data-action="google-login"]'); if (el) { e.stopImmediatePropagation(); signInWithGoogle(); } });
app.addEventListener('click', e => { const el = e.target.closest('[data-action]'); if (!el) return; if (el.dataset.action === 'login') trackMeta('HuggyCtaClick', { placement: el.classList.contains('minimal-cta') ? 'landing' : 'navigation' }, true); if (el.dataset.action === 'plans' && el.dataset.plan) trackMeta('ViewContent', { content_name: el.dataset.plan, content_type: 'subscription' }); });
function checkoutDetailsFromUser() { return { email: state.authUser?.email || '' }; }
function startCheckoutForPlan(plan) { state.checkoutPlan = plan; state.error = ''; state.checkoutLoading = true; state.modal = null; render(); beginCheckout(); }
async function beginCheckout() { if (!state.authUser || !state.checkoutPlan) return; state.checkoutLoading = true; state.error = ''; render(); try { const response = await fetch('/api/checkout', { method: 'POST', headers: { 'Content-Type': 'application/json', ...authHeaders() }, body: JSON.stringify({ plan: state.checkoutPlan, billing: state.billing }) }); const payload = await response.json(); if (!response.ok || !payload.checkoutUrl) { const error = new Error(payload.error || 'Le paiement n’est pas disponible.'); error.status = response.status; throw error; } trackMeta('InitiateCheckout', { content_name: state.checkoutPlan, value: pixelPlanValue(state.checkoutPlan, state.billing), currency: 'XOF' }); window.location.href = payload.checkoutUrl; } catch (error) { state.checkoutLoading = false; state.error = error.message || 'Impossible de préparer le paiement.'; if (error.status === 400 && /profil/i.test(error.message || '')) { state.modal = 'account'; state.accountTab = 'profile'; state.accountEdit = 'profile'; } else state.modal = 'paywall'; render(); } }
app.addEventListener('click', e => { const el = e.target.closest('[data-action]'); if (el?.dataset.action === 'save-profile') { e.stopImmediatePropagation(); saveProfile(); } });
app.addEventListener('click', e => { const el = e.target.closest('[data-action]'); if (!el) return; const a = el.dataset.action; if (a === 'dismiss-promo') state.promo = false; if (a === 'marketing') { state.view = 'marketing'; state.menu = false; } if (a === 'login') { state.view = 'app'; state.menu = false; } if (a === 'language') { state.lang = state.lang === 'fr' ? 'en' : 'fr'; } if (a === 'account') state.menu = !state.menu; if (a === 'account-manage') { state.menu = false; state.modal = 'account'; state.accountTab = 'profile'; state.accountEdit = null; } if (a === 'account-tab') { state.accountTab = el.dataset.tab; state.accountEdit = null; } if (a === 'update-profile') state.accountEdit = 'profile'; if (a === 'update-password') state.accountEdit = 'password'; if (a === 'cancel-account-edit') state.accountEdit = null; if (a === 'email-menu') state.emailMenu = !state.emailMenu; if (a === 'logout') { state.view = 'marketing'; state.menu = false; } if (a === 'collapse') state.collapsed = !state.collapsed; if (a === 'new-file') { state.current = null; state.prompt = ''; state.editPrompt = ''; state.attachedFile = null; state.modal = null; } if (a === 'plans') state.modal = 'paywall'; if (a === 'billing') state.billing = el.dataset.billing || 'monthly'; if (a === 'start-checkout') { state.checkoutPlan = el.dataset.plan; state.checkoutLoading = false; state.error = ''; } if (a === 'back-plans') { state.checkoutPlan = null; state.checkoutLoading = false; state.error = ''; } if (a === 'checkout-submit') { beginCheckout(); return; } if (a === 'open-file') state.current = el.dataset.id; if (a === 'quick') { if (state.current) state.editPrompt = el.dataset.prompt; else state.prompt = el.dataset.prompt; } if (a === 'attach') { const input = el.parentElement?.parentElement?.querySelector('[data-role="file-input"]') || app.querySelector('[data-role="file-input"]'); input?.click(); return; } if (a === 'remove-attachment') state.attachedFile = null; if (a === 'dismiss-error') state.error = ''; if (a === 'dismiss-notice') state.notice = ''; if (a === 'generate') { startGeneration(); return; } if (a === 'preview') { const file = state.files.find(item => item.id === state.current) || state.files[0]; state.modal = 'preview'; state.sheet = workbookSheets(file)[0]?.id || ''; } if (a === 'download') { if (state.plan === 'free') state.modal = 'paywall'; else downloadWorkbook(); } if (a === 'continue') { state.editPrompt = ''; } if (a === 'close-modal') state.modal = null; if (a === 'sheet') state.sheet = el.dataset.sheet; save(); render(); });
app.addEventListener('click', e => { const el = e.target.closest('[data-action]'); if (!el) return; const a = el.dataset.action; if (a === 'login') { state.view = 'marketing'; state.modal = 'auth'; state.authMode = 'login'; state.authError = ''; state.authMessage = ''; } if (a === 'plans') { if (el.dataset.plan) state.pendingCheckoutPlan = el.dataset.plan; if (!state.authUser) { state.modal = 'auth'; state.authMode = 'login'; state.authError = ''; state.authMessage = ''; } else if (el.dataset.plan) { state.checkoutPlan = el.dataset.plan; state.modal = 'paywall'; } } if (a === 'auth-switch') { state.authMode = state.authMode === 'login' ? 'signup' : 'login'; state.authError = ''; state.authMessage = ''; } if (a === 'logout') { signOut(); return; } render(); });
app.addEventListener('click', e => { const el = e.target.closest('[data-action]'); if (!el) return; if (el.dataset.action === 'start-checkout') startCheckoutForPlan(el.dataset.plan); if (el.dataset.action === 'plans' && el.dataset.plan && state.authUser) startCheckoutForPlan(el.dataset.plan); });
app.addEventListener('submit', e => { if (!e.target.matches('[data-role="auth-form"]')) return; e.preventDefault(); beginAuth(); });
app.addEventListener('keydown', e => { if (e.key === 'Enter' && !e.shiftKey && e.target.matches('textarea')) { e.preventDefault(); startGeneration(); } });
app.addEventListener('click', e => { const el = e.target.closest('[data-action]'); if (!el) return; if (el.dataset.action === 'history') { state.modal = 'history'; render(); } if (el.dataset.action === 'restore-version') restoreVersion(el.dataset.version); });
render();
const checkoutReturned = new URLSearchParams(window.location.search).get('checkout') === 'success';
if (checkoutReturned) { history.replaceState({}, '', `${window.location.pathname}${window.location.hash}`); }
hydrateAuth().then(() => { if (checkoutReturned && state.authUser) { syncEntitlement(true); setTimeout(() => syncEntitlement(true), 2500); setTimeout(() => syncEntitlement(true), 7000); } });
